"""Nuevo campo Direccion

Revision ID: 798ea7f4d086
Revises: 54046b993675
Create Date: 2026-01-17 11:21:22.253715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798ea7f4d086'
down_revision = '54046b993675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
